name: bubble_timeline
description: A Flutter Widget to make interactive timeline widget.
version: 1.0.0
homepage: https://github.com/vanshg395/bubble_timeline

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

